### ISSUE TITLE
Any plans for Seek(prefix) ?

### ISSUE THREAD

**Issue by faaliyet** [Photonios/rocksdb-php#2]
As the title explains itself, is it possible to add this feature ?
https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes

example:
http://pyrocksdb.readthedocs.org/en/latest/tutorial/#prefixextractor

Also, it can be valuable to develop something like this for client-server relationship. I've checked that but it's more focused on leveldb rather than rocksdb.
https://github.com/ideawu/ssdb-rocks

**Comment by ghost** [comment]
hmm... I think, that could be more improvements into source to support some new features of rocksdb 3.x.
https://github.com/facebook/rocksdb/wiki/Column-Families
https://github.com/facebook/rocksdb/blob/master/examples/column_families_example.cc
